# Generated by Django 4.2.16 on 2024-10-16 07:27

import Shops.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.FloatField(validators=[Shops.models.validate_latitude])),
                ('longitude', models.FloatField(validators=[Shops.models.validate_longitude])),
            ],
        ),
    ]
